name: validate-atomics
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  validate-atomics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2" # Not needed with a .ruby-version file
      - name: Install gems
        run: |
          gem install json-schema
      - name: Validate atomics
        run: |
          ruby ./bin/validate/validate.rb

  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: false
