name: validate-atomics
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  validate-atomics:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: setup python3.11
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.11.2"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: validate the format of atomics tests against the spec
        run: |
          poetry run python bin/validate/validate.py

  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: false